
services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "Bookie@123"]
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  
      - "9001:9001"  
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/storage;
      exit 0;"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Bookie@123
      MYSQL_USER: kapkap
      MYSQL_PASSWORD: Kapkap@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_backup:/backup
  
volumes:
  redis_data:
  mysql_data:



