listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

webhook:
    host: 0.0.0.0
    port: 8082
    endpoint: /webhook

http_listener:
  tcp:
    address: 0.0.0.0
    port: 8081
    secure: false

sms_gateway:
  address: sms
  port: 3000
  sms_timeout: 90
  webhook_url:  ${SMS_GATEWAY_WEBHOOK_URL}
  
logger:
  pretty: true
  level: DEBUG

database:
  auth_method: ${DATABASE_AUTH_METHOD}
  host: ${DATABASE_HOST}
  port: 3306
  name: ${DATABASE_NAME}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  aws_region: ${DATABASE_AWS_REGION}
  debug: false
  tracing_enabled: false
  max_idle_conns: 5

redis:
  address: ${REDIS_ADDRESS}
  namespace: ${REDIS_NAMESPACE}
  password: ${REDIS_PASSWORD}

