listener:
  tcp:
    address: 0.0.0.0
    port: 8080
    secure: false

logger:
  pretty: false
  level: DEBUG

s3:
  access_key_id: ${S3_ACCESS_KEY_ID}
  secret_access_key: ${S3_SECRET_ACCESS_KEY}
  region: ${S3_REGION}
  bucket: ${S3_BUCKET}
  host: ${S3_HOST}
  endpoint_url: ${S3_ENDPOINT_URL}
  provider: ${S3_PROVIDER:1} # 1 aws, 2 cloudflare


presign:
  conditions:
    min_length: 0  
    max_length: 104857600 #100mb
    expiration_time: 15 #15 minute

setting:
  service_names_allowed:
    - upload


